---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unera-bot
  namespace: cover-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "csi-high-iops-me1-retain"



