FROM debian:trixie

RUN apt-get -yq update
RUN apt-get -yq install \
	golang-go \
	git \
	libmagickwand-dev \
	tree \
	sudo \
	tzdata \
	make \
	procps
ENV TZ=Europe/Moscow

WORKDIR /cover-bot
ENV GOPATH=/cover-bot/go
ENV PATH="/cover-bot/bin:${GOPATH}/bin:${PATH}"
RUN mkdir -p /cover-bot

